server:
  port: 8088

spring:
  profiles:
    active: dev
  application:
    name: @pom.artifactId@
  security:
    user:
      name: admin
      password: admin


info:
  软件著作权: paascloud快速搭建企业级分布式微服务平台
  著作登记号: 2018SR320076
  关于我们: http://paascloud.net